### ISSUE TITLE
Encrypted Shell Broke

### ISSUE THREAD

**Issue by brsmathers** [ZHacker13/ReverseTCPShell#3]
Looks like your recent update may have broke the encrypted script:

![RTCP](https://user-images.githubusercontent.com/31546439/58819492-5d98e780-85fe-11e9-8137-a7fad0b4655d.jpg)

**Comment by ZHacker13** [comment]
Thanks!, I know, i will update the C2 Server listener Soon!
Please wait for "ReverseTCP V2.0"

*** Please Remember that in Reverse Encrypted (AES 256-bit) Shell your Input\Output Max characters is "65,536".
