### ISSUE TITLE
Cannot run your script

### ISSUE THREAD

**Issue by Evro123** [ZHacker13/ReverseTCPShell#7]
When try to run your .ps1 file I get nothing:
```
PS C:\WINDOWS\system32> & "C:\Users\Admin\Desktop\TCP.ps1
>>
>>
>>
>>
>>
```
why?Am I not running it probably?

**Comment by Staubgeborener** [comment]
Yes, you don't run it properly. You miss the last quotation mark at the end.
Wrong: `PS C:\WINDOWS\system32> & "C:\Users\Admin\Desktop\TCP.ps1`
Right: `PS C:\WINDOWS\system32> & "C:\Users\Admin\Desktop\TCP.ps1"`
